### ISSUE TITLE
How to Make All Operations Run on a Certain Thread in iOS

### ISSUE THREAD

**Issue by onmyway133** [duemunk/Thread#1]
Nice library Tobias, I remember struggling this problem before in my post http://www.fantageek.com/blog/2014/09/19/how-to-make-all-operations-run-on-a-certain-thread-in-ios/

Basically it is a lesson learned from AFNetworking on how to leverage NSRunloop to achieve this, hope you find it useful too

**Comment by duemunk** [comment]
Hi @onmyway133 
I'm not sure I follow? Care do elaborate what's missing from **Thread** and why you would add that?

**Comment by onmyway133** [comment]
@duemunk ah, I haven't read the source code of Thread so I don't know what 's missing. But that reminds me that AFNetworking had a solution like that, and want to share with you
